metadata:
  extensions_folder: extensions

categories:
  - name: feature
    description: Extensions that extract features from flows
  - name: inference
    description: Extensions that infer information from flows and requests predictions
  - name: reporting
    description: Extensions that report the results

extensions:
  - id: hello_world_feature_0
    category: feature
    source: https://github.com/AhmedCoolProjects/sonic-engine-hello-world-feature.git
    # controlling the extension default instance configs and duplicated instances configs
    override:
      # Override the default extension instance configs
      hello_world_feature_0:
        branch: main
      # Add a new extension instance
      hello_world_feature_1:
        branch: dup/1
      # A new extension instance by overriding the default local configs coming with the extension
      hello_world_feature_2:
        branch: main
        description: This is a new instance of the hello world feature extension overriding the default configs

  - id: hello_world_inference_0
    category: inference
    source: https://github.com/AhmedCoolProjects/sonic-engine-hello-world-inference.git

  - id: hello_world_reporting_0
    category: reporting
    source: https://github.com/AhmedCoolProjects/sonic-engine-hello-world-reporting.git
